version: '3'
services:
  flask-app:
    image: ghcr.io/violinyanev/my-app-backend:latest
    ports:
      - "5000:5000"

  nginx:
    image: nginx:1.25.0
    ports:
      - "80:80"
    depends_on:
      - flask-app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
